INSERT INTO users (login, password, first_name, last_name) VALUES
('alice', 'pass1', 'Alice', 'Smith'),
('bob', 'pass2', 'Bob', 'Johnson'),
('charlie', 'pass3', 'Charlie', 'Brown'),
('diana', 'pass4', 'Diana', 'Prince'),
('eve', 'pass5', 'Eve', 'Adams'),
('frank', 'pass6', 'Frank', 'Miller'),
('grace', 'pass7', 'Grace', 'Hopper'),
('henry', 'pass8', 'Henry', 'Ford'),
('ivy', 'pass9', 'Ivy', 'Lee'),
('jack', 'pass10', 'Jack', 'Sparrow');

INSERT INTO goals (user_id, title, description) VALUES
(1, 'Learn C++', 'Master userver framework and PostgreSQL'),
(1, 'Read 20 books', 'Fiction and non-fiction'),
(2, 'Travel to Japan', 'Visit Tokyo and Kyoto'),
(2, 'Write a blog', 'About technology and life'),
(3, 'Exercise regularly', 'At least 3 times a week'),
(3, 'Learn cooking', 'Prepare 10 new recipes'),
(4, 'Save money', 'Save 1000$ by end of year'),
(5, 'Learn Spanish', 'Reach B1 level'),
(6, 'Build a mobile app', 'Simple task manager'),
(7, 'Contribute to open source', 'At least 5 PRs'),
(8, 'Start a podcast', 'On software engineering'),
(9, 'Improve public speaking', 'Join Toastmasters'),
(10, 'Learn guitar', 'Play 3 songs');

INSERT INTO tasks (goal_id, title, status) VALUES
(1, 'Read userver docs', 'done'),
(1, 'Setup PostgreSQL container', 'done'),
(1, 'Implement repositories', 'in_progress'),
(2, 'Buy books', 'todo'),
(2, 'Read "Clean Code"', 'todo'),
(3, 'Book flights', 'todo'),
(3, 'Reserve hotels', 'todo'),
(4, 'Write first post', 'done'),
(4, 'Publish on Medium', 'in_progress'),
(5, 'Go to gym Monday', 'todo'),
(5, 'Run 5km', 'done'),
(6, 'Find recipes online', 'done'),
(6, 'Cook pasta carbonara', 'todo'),
(7, 'Set up automatic transfer', 'done'),
(8, 'Install Duolingo', 'done'),
(8, 'Complete 10 lessons', 'in_progress'),
(9, 'Design UI', 'todo'),
(10, 'Find a project', 'todo'),
(11, 'Buy microphone', 'todo'),
(12, 'Attend first meeting', 'todo'),
(13, 'Tune guitar', 'done');